name: Run main.py on GitHub-hosted Runner

on:
  push:
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run main.py
        run: python main.py
