name: Python Test on GitHub-hosted Runner

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Python script
        run: |
          python --version
          echo "print('Hello from GitHub Actions')" > hello.py
          python hello.py
